# Generated by Django 4.2.2 on 2023-07-15 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='book',
            field=models.CharField(default='abcd', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='excited',
            field=models.CharField(default='abcd', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(default='abcd', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='food',
            field=models.CharField(default='abcd', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='l_name',
            field=models.CharField(default='abcd', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.CharField(default='abcd', max_length=255),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
